# site settings
title: Molnár Tímea
subtitle: 
email: move.grow.mt@gmail.com
description: 'Üdvözöllek a személyes weboldalomon! <br/> Angol nyelvórák és játékos foglalkozások Alsóörsön, gyermekeknek és felnőtteknek, egyéni és kiscsoportos formában.<br/>Reformer Pilates órák Balatonalmádiban, a Pilates Flow Studioban, magyar és angol nyelven.<br/><br/> Welcome to my website! <br/> Reformer Pilates classes are available in English at the Pilates Flow Studio in Balatonalmádi. </br> Find all the details about Reformer Pilates in English in the section below. <br/> ' 
baseurl:  # the subpath of your site, e.g. /blog
url: https://www.molnartimea.hu # the base hostname & protocol for your site
author:
street_address: 
city: Alsóörs, Balatonalmádi
state: 
zip_code: 
country: 
phone: +36 20 512 3644

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 5

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: 
  GitLab:
  Google-Plus: 
  Instagram: 
  LinkedIn: 
  Twitter: 
  Facebook: https://www.facebook.com/tomi.timi.77
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
