# site settings
title: Molnár Tímea
subtitle: 
email: move.grow.mt@gmail.com
description: 'Üdvözöllek a személyes weboldalomon! <br/> Az angol nyelvórák és foglalkozások helyszíne Alsóörs. <br/> Pilates óráim Balatonalmádiban, a Pilates Flow Studioban érhetőek el. <br/> Pilates classes are also available in English in the Pilates Flow Studio, Balatonalmádi.' 
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 
city: Alsóörs, Balatonalmádi
state: 
zip_code: 
country: 
phone: +36 20 512 3644

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 5

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: 
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: 
  Twitter: 
  Facebook: 
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
